// Notes data for the Principles of Microeconomics course
export const principlesOfMicroeconomicsNotes: { [key: string]: { title: string; content: string } } = {
  // Module 1, Lesson 1
  '1-1': {
    title: 'Understanding Scarcity and Choice',
    content: `
# Core Concepts
    
*   Economics studies decision-making under **scarcity**, where unlimited wants meet limited resources, necessitating **tradeoffs**.
*   **Microeconomics** focuses on the decisions of individual **households and firms**, while **Macroeconomics** examines economy-wide phenomena and government tradeoffs.
*   Economists use simplified **models** (mathematical representations) to understand complex real-world interactions, acknowledging that models are abstractions ("wrong") but useful for isolating key forces.
*   Sound economic decision-making relies on understanding **opportunity cost** (value of the forgone alternative), ignoring **sunk costs** (unrecoverable past expenses), and applying the **marginal principle** (comparing incremental benefits and costs).
*   The **model of demand and supply** is a fundamental tool used to analyze behavior in **markets**, particularly **perfectly competitive markets**.
    
# Key Term Definitions
    
*   **Economics**: The study of how society manages its scarce resources; fundamentally, the study of decision-making in the presence of scarcity or tradeoffs.
*   **Scarcity**: The limited nature of society's resources relative to unlimited wants.
*   **Tradeoff**: The necessity of giving up one thing to obtain another due to scarcity.
*   **Microeconomics**: The branch of economics that studies the behavior of individual economic units, such as households and firms, and their interactions in markets.
*   **Macroeconomics**: The branch of economics that studies economy-wide phenomena, including inflation, unemployment, economic growth, and government policy.
*   **Model**: A simplified mathematical representation of reality used to better understand real-world phenomena by focusing on key variables and relationships.
*   **Opportunity Cost**: The value of the best alternative that must be forgone to undertake an activity or make a decision. Often an implicit, non-obvious cost.
*   **Sunk Cost**: A cost that has already been incurred and cannot be recovered, regardless of future decisions.
*   **Marginal Principle**: A decision-making heuristic stating that an activity should be increased as long as the marginal benefit is greater than or equal to the marginal cost.
*   **Market**: A group of buyers and sellers of a particular good or service.
*   **Demand**: The relationship between the price of a good and the quantity buyers are willing and able to purchase.
*   **Supply**: The relationship between the price of a good and the quantity sellers are willing and able to sell.
*   **Efficiency**: The property of society getting the maximum benefits from its scarce resources (maximizing the size of the economic pie).
*   **Equity**: The property of distributing economic prosperity fairly among the members of society (how the economic pie is divided).
    
# Scarcity and Tradeoffs
    
## Scarcity and Tradeoffs - Definition
Scarcity refers to the fundamental economic problem of having seemingly infinite human wants in a world of limited resources. A tradeoff is the consequence of scarcity, requiring that choosing more of one thing necessitates having less of something else.
    
## Scarcity and Tradeoffs - Key Insights
All economic decisions, whether by individuals, firms, or governments, involve navigating tradeoffs because resources (time, money, materials) are always limited relative to potential uses. Economics is essentially the study of these choices.
    
## Scarcity and Tradeoffs - Examples
*   A car manufacturer with limited microchips must decide which models receive the chips, trading off production of one model for another.
*   A firm with a fixed advertising budget must choose which products to promote, trading off exposure for one product against another.
    
# Efficiency versus Equity
    
## Efficiency versus Equity - Definition
*   **Efficiency**: Maximizing the total output or benefit generated from available scarce resources.
*   **Equity**: Distributing the benefits generated by resources fairly or equally among society's members.
    
## Efficiency versus Equity - Key Insights
There is often a conflict between efficiency and equity. Policies designed to increase equity (e.g., progressive taxes funding social programs) can sometimes reduce incentives for production, thereby potentially lowering overall efficiency. Understanding this tradeoff is crucial for policy analysis.
    
## Efficiency versus Equity - Examples
*   Implementing high taxes on businesses to fund unemployment benefits might enhance equity but could reduce firms' incentives to invest and expand (lowering efficiency).
    
# Opportunity Cost
    
## Opportunity Cost - Definition
The value of the next best alternative that is given up when making a choice. It represents the true cost of a decision.
    
## Opportunity Cost - Key Insights
Opportunity costs are often implicit (not involving a direct cash outlay) and are frequently overlooked, leading to suboptimal decisions. Recognizing and quantifying opportunity cost is essential for accurate cost-benefit analysis.
    
## Opportunity Cost - Examples
*   **Education**: The opportunity cost of pursuing an online BBA includes the potential income forgone by not working during study time.
*   **Consumption**: For affluent individuals during COVID lockdowns with limited spending options, the opportunity cost of money was low, making niche purchases (like "flights to nowhere") seem more appealing than they would be otherwise.
*   **Business Choice**: A handyman choosing to open a shop must consider the forgone earnings from his handyman work as an opportunity cost of his time. Ignoring this led Ramesh to choose a less profitable option (shop profit Rs. 20,000 vs. inventory sale profit Rs. 10,000 + handyman income Rs. 15,000 = Rs. 25,000).
    
# Sunk Cost
    
## Sunk Cost - Definition
Costs that have already been incurred and cannot be recovered or changed by present or future decisions.
    
## Sunk Cost - Key Insights
Sunk costs are irrelevant to future decision-making. Rational decisions should be based only on future costs and benefits. Considering sunk costs (the "sunk cost fallacy") often leads to irrational choices, like continuing a failing project to "justify" past investment.
    
## Sunk Cost - Examples
*   **Entertainment**: Money spent on a non-refundable movie ticket is sunk. Staying to watch a bad movie solely because the ticket was paid for is irrational; the cost is unrecoverable, and staying incurs the additional cost of wasted time and discomfort.
*   **Travel**: When deciding between driving and taking a bus, fixed car costs like annual insurance or past interest payments are sunk. They should be ignored. Only variable costs (fuel, incremental maintenance) relevant to the specific trip should be compared to the bus fare. (Relevant car cost for 600km trip ≈ Rs 1320 vs. Bus fare Rs 1500).
    
# Marginal Principle
    
## Marginal Principle - Definition
The principle that rational decision-makers take an action if and only if the marginal benefit (MB) of the action is greater than or equal to the marginal cost (MC).
*   **Marginal Benefit (MB)**: The additional benefit arising from a one-unit increase in an activity.
*   **Marginal Cost (MC)**: The additional cost arising from a one-unit increase in an activity.
    
## Marginal Principle - Key Insights
To maximize net benefit (total benefit - total cost), decisions should be made "at the margin." Comparing average benefits and costs can be misleading. The optimal level of an activity is reached when MB = MC.
*   Consumers maximize utility where Marginal Utility ≥ Price.
*   Firms maximize profit where Marginal Revenue ≥ Marginal Cost.
    
## Marginal Principle - Examples
*   **Business Expansion (Rahul's Bookstores)**: Comparing average benefit (Rs. 140k) to average cost (Rs. 100k) suggested opening a 4th store was good. However, the marginal benefit of the 4th store (Rs. 50k) was less than its marginal cost (Rs. 100k). Applying the marginal principle correctly showed that opening the 4th store would *decrease* total profit, and the optimal number was 3 stores.
    
## Marginal Principle - Formula
Decision Rule: Undertake one additional unit of activity if **MB ≥ MC**. Stop when **MB < MC**.
    
# The Model of Demand and Supply
    
## Markets
    
### Markets - Definition
A setting where potential buyers and sellers interact to exchange a particular good or service.
    
### Markets - Key Insights
Markets differ based on structure, primarily the number and size of buyers and sellers, and the uniformity of the product. This course initially focuses on perfectly competitive markets.
    
### Comparisons (Types of Markets)
*   **Perfectly Competitive Market**: Many small buyers and sellers, identical products, no single participant can influence price (price takers).
*   **Oligopoly**: Few large sellers dominate the market.
*   **Monopoly**: A single seller controls the market.
---

## Demand
    
### Demand - Definition
**Quantity Demanded**: The amount of a good buyers are willing and able to purchase at a specific price, ceteris paribus (holding other factors constant).
    
### Demand - Key Insights
*   **Law of Demand**: Quantity demanded decreases as price increases (inverse relationship), resulting in a downward-sloping demand curve.
*   **Movement along the Curve**: Caused by a change in the good's own price.
*   **Shift of the Curve**: Caused by a change in any determinant *other than* the good's own price (increase = rightward shift, decrease = leftward shift).
*   **Market Demand**: The horizontal summation of individual demands at each price level.
    
### Examples (Factors Shifting Demand)
*   **Income**: Increase shifts demand right for *normal goods*, left for *inferior goods*.
*   **Prices of Related Goods**:
      *   Increase in substitute's price shifts demand right.
      *   Increase in complement's price shifts demand left.
*   **Preferences/Tastes**: Favorable change shifts demand right.
*   **Expectations**: Expectation of future price increase shifts current demand right.
*   **Number of Buyers**: Increase shifts market demand right.
*   *(Practice Problem Insight)*: A demand function like QX = f(Px, Py, I, ...) shows relationships. A positive coefficient on Py indicates X and Y are substitutes; a negative coefficient on I indicates X is an inferior good.
---
   
## Supply
    
### Supply - Definition
**Quantity Supplied**: The amount of a good sellers are willing and able to sell at a specific price, ceteris paribus.
    
### Supply - Key Insights
*   **Law of Supply**: Quantity supplied increases as price increases (positive relationship), resulting in an upward-sloping supply curve. Higher prices incentivize using more resources (potentially higher cost ones) for production.
*   **Movement along the Curve**: Caused by a change in the good's own price.
*   **Shift of the Curve**: Caused by a change in any determinant *other than* the good's own price (increase = rightward shift, decrease = leftward shift).
*   **Market Supply**: The horizontal summation of individual supplies at each price level.
    
### Examples (Factors Shifting Supply)
*   **Technology**: Improvement shifts supply right.
   *   **Prices of Inputs**: Decrease shifts supply right; increase shifts supply left.
   *   **Expectations**: Expectation of future price decrease shifts current supply right; expectation of future price increase shifts current supply left (hoarding).
   *   *(Practice Problem Insight)*: A supply function like Qsx = f(Px, Pi, ...) shows relationships. A negative coefficient on input price (Pi) reflects the principle that higher input costs reduce supply.
    
# Conclusion
    
The fundamental economic problem of scarcity forces individuals and firms to make choices involving tradeoffs. Microeconomics provides a framework for analyzing these decisions using core concepts like opportunity cost (consider implicit costs), sunk cost (ignore past, unrecoverable costs), and the marginal principle (compare incremental benefits and costs). These individual decisions aggregate within markets, where the interplay of demand (buyer behavior) and supply (seller behavior) determines prices and quantities, a dynamic powerfully illustrated by the demand and supply model. Understanding these principles is crucial for informed decision-making in both personal and business contexts.
    
    
    
    `
  },
  
  // Module 2, Lesson 1
  '2-1': {
    title: 'Exploring Market Equilibrium',
    content: `
# Core Concepts

*   Markets consist of buyers (demand) and sellers (supply), interacting to determine prices and quantities.
*   Market equilibrium occurs where quantity demanded equals quantity supplied, resulting in an equilibrium price (P*) and quantity (Q*).
*   Market forces naturally push prices towards equilibrium, coordinating economic activity efficiently (the "invisible hand").
*   Economic well-being is measured by consumer surplus (value to buyers minus price paid) and producer surplus (price received minus cost to sellers); market equilibrium maximizes total surplus.
*   Elasticity measures the responsiveness of quantity demanded or supplied to changes in price, income, or related goods' prices, impacting revenue and tax incidence.
*   Government interventions like taxes and price controls can shift market equilibrium, affecting prices, quantities, surplus, and potentially creating deadweight loss or shortages/surpluses.

# Key Terms Definitions
*   **Demand Curve:** A graphical representation showing the relationship between the price of a good and the quantity demanded by consumers, holding other factors constant.
*   **Supply Curve:** A graphical representation showing the relationship between the price of a good and the quantity supplied by producers, holding other factors constant.
*   **Law of Demand:** The principle that, other factors being equal, the quantity demanded of a good falls when its price rises, resulting in a downward-sloping demand curve.
*   **Market Equilibrium:** The state where the supply and demand curves intersect, meaning the quantity demanded equals the quantity supplied at the prevailing price.
*   **Equilibrium Price (P\*):** The price at which quantity demanded equals quantity supplied; the market-clearing price.
*   **Equilibrium Quantity (Q\*):** The quantity bought and sold at the equilibrium price.
*   **Consumer Surplus (CS):** The difference between a buyer's willingness to pay for a good and the amount actually paid. Graphically, the area below the demand curve and above the market price.
*   **Producer Surplus (PS):** The difference between the amount a seller is paid for a good and their cost of producing it (or willingness to sell). Graphically, the area below the market price and above the supply curve.
*   **Total Surplus (TS):** The sum of consumer surplus and producer surplus (TS = CS + PS), representing the total economic well-being derived from a market. Also equivalent to the total value to buyers minus the total cost to sellers.
*   **Efficiency:** An allocation of resources that maximizes total surplus.
*   **Inefficiency:** An allocation of resources where total surplus is not maximized, implying potential gains from trade are unrealized.
*   **Elasticity:** A measure of the responsiveness of one variable (e.g., quantity demanded) to a change in another variable (e.g., price).
*   **Price Elasticity of Demand (EP):** A measure of how much the quantity demanded of a good responds to a change in its price.
*   **Price Elasticity of Supply (ES):** A measure of how much the quantity supplied of a good responds to a change in its price.
*   **Tax Incidence:** The manner in which the burden of a tax is shared between buyers and sellers.
*   **Deadweight Loss (DWL):** The reduction in total surplus that results from a market distortion, such as a tax or price control.
*   **Price Cap (Price Ceiling):** A legal maximum on the price at which a good can be sold.
*   **Price Floor:** A legal minimum on the price at which a good can be sold.


# Market Equilibrium
## Market Equilibrium - Definition
The point where the market demand curve and market supply curve intersect, determining the market-clearing price and quantity.
## Market Equilibrium - Key Insights
*   Demand curve slopes downward (Law of Demand).
*   Supply curve typically slopes upward.
*   At equilibrium (P*, Q*), quantity demanded equals quantity supplied.
*   If Price > P*, excess supply occurs, leading to downward pressure on price. Seller symptoms: infrequent consumers, rising inventory.
*   If Price < P*, excess demand occurs, leading to upward pressure on price. Seller symptoms: inventory vanishes quickly, potential queues.
*   Self-interested actions of buyers and sellers drive the market towards equilibrium.

# Invisible Hand of Prices
## Invisible Hand of Prices - Definition
The concept that individual self-interest in competitive markets, guided by the price mechanism, leads to a socially desirable allocation of resources without central coordination.
## Invisible Hand of Prices - Key Insights
*   Prices coordinate the actions of numerous independent buyers and sellers.
*   No central planner is needed to determine production levels, consumption patterns, or prices.
*   The market mechanism tends to guide resources towards their most valued uses, achieving a social optimum (efficiency).

# Analyzing Market Changes
## Analyzing Market Changes - Definition
A systematic process to determine how an external event affects market equilibrium price and quantity.
## Analyzing Market Changes - Key Insights
*   Step 1: Identify the relevant market(s).
*   Step 2: Determine if the event shifts the demand curve, the supply curve, or both.
*   Step 3: Determine the direction of the shift (left/decrease or right/increase).
*   Step 4: Use the supply-demand diagram to compare the old and new equilibrium points (P*, Q*).
## Analyzing Market Changes - Examples
*   **Input Cost Increase:** Fire at chip plant (input for cars) → Shifts car supply curve left → Increases car equilibrium price.
*   **Related Goods Price Change:** Higher new car prices → Shifts used car demand curve right → Increases used car equilibrium price.
*   **Supply Shock:** Conflict reducing crude oil supply → Shifts crude oil supply curve left → Increases crude oil price. This subsequently increases costs for synthetic fibers (using oil as input) → Shifts fiber supply curve left → Increases fiber prices.

# Measures of Economic Well-being
## Consumer Surplus (CS)
### Consumer Surplus (CS) - Definition
The benefit buyers receive from participating in a market, measured as their willingness to pay minus the price actually paid.
### Consumer Surplus (CS) - Key Insights
*   Represents the monetary value of utility/happiness gained beyond the expenditure.
*   Calculated as the area below the demand curve and above the price line, up to the quantity consumed.
*   The height of the demand curve reflects the marginal buyer's willingness to pay.
### Consumer Surplus (CS) - Formula Concept
CS = Area (Below Demand Curve, Above Price) = Σ (Willingness to Pay - Price) for all units bought.

## Producer Surplus (PS)
### Producer Surplus (PS) - Definition
The benefit sellers receive from participating in a market, measured as the amount received minus their cost of production (including opportunity cost).
### Producer Surplus (PS) - Key Insights
*   Represents profit beyond the minimum acceptable price (cost/willingness to sell).
*   Calculated as the area below the price line and above the supply curve, up to the quantity sold.
*   The height of the supply curve reflects the marginal seller's cost or willingness to sell.
### Producer Surplus (PS) - Formula Concept
PS = Area (Below Price, Above Supply Curve) = Σ (Price - Cost) for all units sold.

## Total Surplus (TS)
### Total Surplus (TS) - Definition
The sum of consumer surplus and producer surplus, measuring the overall economic well-being generated by a market.
### Total Surplus (TS) - Key Insights
*   Represents the total gains from trade in a market.
*   Market equilibrium maximizes this value under ideal conditions.
### Total Surplus (TS) - Formula
TS = CS + PS
TS = (Value to Buyers) - (Cost to Sellers)

# Efficiency
## Efficiency - Definition
An allocation of resources that maximizes total surplus.
## Efficiency - Key Insights
*   Market equilibrium outcome is typically efficient.
*   Inefficiency arises if:
    1.  Potential gains from trade are missed.
    2.  Goods aren't allocated to buyers with the highest willingness to pay.
    3.  Production isn't allocated to sellers with the lowest costs.
*   A benevolent social planner aiming to maximize well-being would ideally let the free market reach equilibrium.
## Efficiency - Comparisons
*   **Efficient Allocation:** Total surplus is maximized (e.g., market equilibrium).
*   **Inefficient Allocation:** Total surplus is below its potential maximum (e.g., due to taxes, price controls, or market failures).

# Elasticity
## Elasticity - Definition
A measure of the sensitivity or responsiveness of one variable to a change in another.
## Price Elasticity of Demand (EP)
### Price Elasticity of Demand (EP) - Definition
Measures how much quantity demanded changes in response to a price change.
### Price Elasticity of Demand (EP) - Key Insights
*   Always negative, but often expressed as an absolute value.
*   Factors affecting EP: Availability of substitutes, narrowness of definition, budget share, time horizon.
*   Along a linear demand curve (P = A - BQ), EP varies: perfectly elastic at P-intercept, elastic above midpoint, unit elastic at midpoint, inelastic below midpoint, perfectly inelastic at Q-intercept.
*   Relationship with Total Revenue (TR = P * Q):
    *   If demand is inelastic (EP < 1), ↑P leads to ↑TR.
    *   If demand is elastic (EP > 1), ↑P leads to ↓TR.
    *   If demand is unit elastic (EP = 1), ↑P leads to no change in TR.
### Price Elasticity of Demand (EP) - Formula
EP = | (% Change in Quantity Demanded) / (% Change in Price) |
### Price Elasticity of Demand (EP) - Comparisons
*   **Perfectly Inelastic (EP = 0):** Quantity demanded does not change regardless of price (vertical demand curve).
*   **Inelastic (EP < 1):** %ΔQd < %ΔP. Quantity demanded is relatively unresponsive to price.
*   **Unitary Elastic (EP = 1):** %ΔQd = %ΔP.
*   **Elastic (EP > 1):** %ΔQd > %ΔP. Quantity demanded is relatively responsive to price.
*   **Perfectly Elastic (EP = ∞):** Any price increase causes quantity demanded to drop to zero (horizontal demand curve).

## Elasticity - Other Elasticities
### Other Elasticities - Definitions
*   **Income Elasticity of Demand (EI):** Measures responsiveness of quantity demanded to changes in consumer income.
*   **Cross-Price Elasticity of Demand:** Measures responsiveness of quantity demanded of Good A to changes in the price of Good B.
*   **Price Elasticity of Supply (ES):** Measures responsiveness of quantity supplied to changes in the selling price.
### Other Elasticities - Key Insights
*   **EI:** Positive for normal goods, negative for inferior goods.
*   **Cross-Price:** Positive for substitutes (↑PB → ↑QdA), negative for complements (↑PB → ↓QdA).
*   **ES:** Depends on production flexibility and time horizon. Supply is more elastic in the long run.
### Other Elasticities - Formulas
*   EI = (% Change in Quantity Demanded) / (% Change in Income)
*   Cross-Price Elasticity = (% Change in Qd of Good A) / (% Change in Price of Good B)
*   ES = (% Change in Quantity Supplied) / (% Change in Price)
### Other Elasticities - Comparisons (Supply)
*   **Perfectly Inelastic (ES = 0):** Vertical supply curve.
*   **Inelastic (0 < ES < 1):** Steep supply curve.
*   **Unitary Elastic (ES = 1):** Supply curve passes through origin (if linear).
*   **Elastic (ES > 1):** Flat supply curve.
*   **Perfectly Elastic (ES = ∞):** Horizontal supply curve.

# Government Policies and Market Equilibrium
## Tax Incidence
### Tax Incidence - Definition
The study of how the burden of a tax is distributed between buyers (consumers) and sellers (producers).
### Tax Incidence - Key Insights
*   A specific tax (T) per unit on sellers shifts the supply curve vertically upwards by the amount T.
*   New equilibrium: Higher price for buyers (Pb), lower price received by sellers (Ps), lower quantity (Q hat).
*   The burden falls more heavily on the side of the market that is less elastic.
    *   If Demand is more inelastic than Supply → Buyers bear more burden.
    *   If Supply is more inelastic than Demand → Sellers bear more burden.
*   Taxes create a deadweight loss (DWL) – a reduction in total surplus because mutually beneficial trades are prevented. DWL is larger when demand or supply is more elastic.
### Tax Incidence - Example
Luxury tax on yachts (likely elastic demand): Producers bear most of the burden.
### Tax Incidence - Formulas
*   Ps = Pb - T
*   DWL = Area of triangle between Supply and Demand curves, from Q hat to Q*

## Price Controls
### Price Controls - Definition
Government-mandated maximum (ceiling) or minimum (floor) prices.
### Price Controls - Key Insights
*   **Price Ceiling (Cap):** To be effective (binding), must be set *below* the equilibrium price (P*). Creates excess demand (shortage).
*   **Price Floor:** To be effective (binding), must be set *above* the equilibrium price (P*). Creates excess supply (surplus).
### Price Controls - Comparisons
*   **Effective Price Ceiling:** P < P* → Qd > Qs (Shortage)
*   **Effective Price Floor:** P > P* → Qs > Qd (Surplus)

# Conclusion

This module explores how markets function through the interaction of supply and demand, naturally gravitating towards an equilibrium that maximizes total surplus (economic efficiency) via the "invisible hand" mechanism. The concept of elasticity is crucial for understanding how changes in prices, income, or related goods affect quantities and total revenue, and how the burden of taxes is distributed. Government interventions, such as taxes and price controls, directly impact market outcomes, often leading to shifts in equilibrium, changes in surplus distribution, and potential inefficiencies like deadweight losses or shortages/surpluses.
    `
  },
  
  // Module 3, Lesson 1
  '3-1': {
    title: 'Firm Behavior and Market Power',
    content: `
# Core Concepts

*   Firms are assumed to operate with the primary objective of **maximizing economic profit**.
*   Profit calculation requires understanding both **Total Revenue (TR)** (from sales) and **Total Economic Cost**, which includes explicit monetary outlays and implicit opportunity costs.
*   A firm's **Production Function** dictates the relationship between inputs and outputs, influencing its cost structure, often characterized by **Diminishing Marginal Product**.
*   The **Market Structure** (e.g., perfect competition) significantly impacts a firm's pricing power and revenue generation.
*   Firms make optimal output decisions by comparing **Marginal Revenue (MR)** and **Marginal Cost (MC)**.
*   Operational decisions (shutdown, exit) depend on comparing price to average variable cost (short run) and average total cost (long run).

# Key Term Definitions
*   **Firm:** An entity that combines inputs (labor, capital, materials) to produce goods or services for sale.
*   **Profit:** The difference between total revenue and total cost.
*   **Total Revenue (TR):** The total amount of money received from the sale of a firm's output.
*   **Total Cost (TC):** The market value of all inputs used in production, including both explicit and implicit costs.
*   **Explicit Costs:** Input costs requiring a direct outlay of money by the firm.
*   **Implicit Costs:** Input costs that do not require an outlay of money; they represent the opportunity cost of using resources owned by the firm (e.g., forgone wages, forgone interest).
*   **Economic Profit:** Total Revenue minus Total Economic Cost (Explicit + Implicit Costs).
*   **Accounting Profit:** Total Revenue minus Total Explicit Cost.
*   **Production Function:** The relationship between the quantity of inputs used to make a good and the quantity of output produced.
*   **Marginal Product (MP):** The increase in output arising from an additional unit of a specific input, holding other inputs constant.
*   **Perfect Competition:** A market structure with many buyers and sellers, identical products, and free entry/exit, where individual firms are price takers.

# The Objective of the Firm
## The Objective of the Firm - Definition
*   The primary goal assumed for firms in standard microeconomic analysis is the maximization of **economic profit**.

## The Objective of the Firm - Key Insights
*   While firms might have other goals (social impact, market share), long-term financial sustainability necessitates profitability.
*   **Economic profit** guides decision-making as it accounts for all costs, including the opportunity cost of the owners' resources.

# Understanding Costs
## Understanding Costs - Definition
*   **Total Cost (TC):** The sum of all costs incurred in production. Can be divided into various categories.

## Understanding Costs - Cost Types & Classification
*   **Explicit vs. Implicit Costs:**
    *   *Explicit:* Direct payments (wages, rent, materials).
    *   *Implicit:* Opportunity costs of using self-owned resources (forgone salary, forgone interest).
*   **Economic vs. Accounting Costs:**
    *   *Economic Cost:* Explicit Costs + Implicit Costs.
    *   *Accounting Cost:* Explicit Costs only.
*   **Fixed vs. Variable Costs:**
    *   **Fixed Costs (FC):** Costs that do not change with the quantity of output produced (e.g., rent). Incurred even if output is zero.
    *   **Variable Costs (VC):** Costs that vary directly with the quantity of output produced (e.g., raw materials, hourly labor).
*   **Sunk Costs:** Costs already incurred that cannot be recovered. They are irrelevant to future production decisions.

## Understanding Costs - Key Insights
*   Economic costs provide a more comprehensive measure for decision-making than accounting costs.
*   The distinction between fixed and variable costs is crucial for short-run decisions. Fixed costs are often irrelevant for the *marginal* decision of producing one more unit but are relevant for the overall profitability assessment.
*   Sunk costs should be ignored when making decisions about future actions, as they cannot be changed.

## Understanding Costs - Comparisons
*   **Economic vs. Accounting Profit:** Economic Profit = **TR** - (Explicit + Implicit Costs); Accounting Profit = **TR** - Explicit Costs. Therefore, Economic Profit ≤ Accounting Profit. Firms aim to maximize Economic Profit.
*   **Fixed vs. Sunk Costs:** Fixed costs are ongoing obligations tied to fixed inputs (relevant for profit calculation), while sunk costs are past, unrecoverable expenditures (irrelevant for current output decisions).

## Understanding Costs - Formula
> Total Cost (**TC**) = Fixed Costs (**FC**) + Variable Costs (**VC**)

# Production and Costs
## Production and Costs - Definition
*   **Production Function:** Describes the technological relationship transforming inputs into outputs.
*   **Marginal Product (MP):** The additional output produced by using one more unit of an input.

## Production and Costs - Key Insights
*   **Diminishing Marginal Product:** A common property where the marginal product of an input declines as the quantity of the input increases, holding other inputs fixed. This implies that producing additional output requires increasingly larger amounts of the variable input.
*   The shape of the total cost curve is directly related to the production function. **Diminishing marginal product** leads to an increasing marginal cost, causing the total cost curve to become steeper as output increases.

## Production and Costs - Examples
*   Adding more workers (variable input) to a kitchen with fixed equipment (fixed input). Initially, output increases significantly, but eventually, workers get in each other's way, and the contribution of each additional worker (**MP**) falls.

# Cost Curves in the Short Run
## Cost Curves in the Short Run - Definition
*   Curves representing the relationship between a firm's costs and its level of output in the short run (when at least one input is fixed).

## Cost Curves in the Short Run - Key Cost Measures & Curves
*   **Total Cost (TC):** **TC** = **FC** + **VC**. Rises as output increases.
*   **Average Fixed Cost (AFC):** **AFC** = **FC** / **Q**. Always decreases as output (**Q**) increases.
*   **Average Variable Cost (AVC):** **AVC** = **VC** / **Q**. Typically U-shaped due initially to increasing returns/efficiency and later to diminishing marginal product.
*   **Average Total Cost (ATC):** **ATC** = **TC** / **Q** = **AFC** + **AVC**. Typically U-shaped. The minimum point of the **ATC** curve represents the **efficient scale** of production.
*   **Marginal Cost (MC):** **MC** = Δ**TC** / Δ**Q**. The cost of producing one additional unit. Typically rises with output due to diminishing marginal product.

## Cost Curves in the Short Run - Key Insights
*   The U-shape of **ATC** reflects the interplay between falling **AFC** and rising **AVC** (driven by **MC**).
*   The **MC** curve intersects both the **AVC** and **ATC** curves at their respective minimum points.
    *   If **MC** < **ATC**, **ATC** is falling.
    *   If **MC** > **ATC**, **ATC** is rising.
    *   If **MC** = **ATC**, **ATC** is at its minimum. (Similar logic applies to **MC** and **AVC**).

## Cost Curves in the Short Run - Formula
> **AFC** = **FC** / **Q**

> **AVC** = **VC** / **Q**

> **ATC** = **TC** / **Q** = **AFC** + **AVC**

> **MC** = Δ**TC** / Δ**Q** (where Δ denotes 'change in')

# Firm Behavior in Perfectly Competitive Markets
## Firm Behavior in Perfectly Competitive Markets - Definition
*   A market structure characterized by: (1) Many buyers and sellers, (2) Homogeneous (identical) products, (3) Free entry and exit in the long run.

## Firm Behavior in Perfectly Competitive Markets - Key Insights
*   Firms in perfect competition are **price takers**, meaning they must accept the market price determined by overall supply and demand. They cannot influence the price.
*   The demand curve facing an individual competitive firm is perfectly elastic (horizontal) at the market price.
*   For a competitive firm, the price is equal to both its average revenue and its marginal revenue.

## Firm Behavior in Perfectly Competitive Markets - Formula
> Average Revenue (**AR**) = **TR** / **Q** = (**P** * **Q**) / **Q** = **P**

> Marginal Revenue (**MR**) = Δ**TR** / Δ**Q** = **P** (since each additional unit sells for the market price **P**)

> Therefore, in Perfect Competition: **P** = **AR** = **MR**

# Profit Maximization
## Profit Maximization - Definition
*   The process by which a firm determines the price and output level that returns the greatest profit.

## Profit Maximization - Key Insights
*   Firms use the **marginal principle**: Increase activity (production) if marginal benefit (**MR**) exceeds marginal cost (**MC**); decrease activity if **MC** exceeds **MR**.
*   The profit-maximizing output level is found where **Marginal Revenue equals Marginal Cost (MR = MC)**.
*   For a perfectly competitive firm, since **P = MR**, the rule becomes: **Produce the quantity where Price equals Marginal Cost (P = MC)**. The relevant portion is where **MC** is rising.

## Profit Maximization - Examples
*   If **P** = $10 and **MC** of the next unit is $8, producing it adds $2 to profit ($10 revenue - $8 cost).
*   If **P** = $10 and **MC** of the next unit is $12, producing it reduces profit by $2 ($10 revenue - $12 cost).
*   Profit is maximized when producing the last unit for which **P** ≥ **MC**.

## Profit Maximization - Graphical Representation
*   Profit = (**P** - **ATC**) * **Q**
*   If **P** > **ATC** at the profit-maximizing quantity (where **P**=**MC**), the firm earns positive economic profit.
*   If **P** < **ATC** at the profit-maximizing quantity, the firm incurs an economic loss.
*   If **P** = **ATC** at the profit-maximizing quantity, the firm earns zero economic profit (break-even).

## Profit Maximization - Formula
> Profit Maximization Rule: **MR** = **MC**

> In Perfect Competition: **P** = **MC**

# Operational Decisions and Supply
## Operational Decisions and Supply - Definition
*   Decisions firms make about whether to produce or not, based on market conditions and costs, in the short run and long run.

## Operational Decisions and Supply - Short-Run Decision: Shutdown
*   **Condition:** A firm should temporarily shut down if the revenue from producing does not cover its variable costs. Fixed costs are irrelevant as they must be paid anyway.
*   **Rule:** Shut down if **Total Revenue < Total Variable Cost (TR < VC)** or, equivalently, if **Price < Average Variable Cost (P < AVC)**.
*   **Short-Run Supply Curve:** The portion of the firm's **Marginal Cost (MC)** curve that lies **above** its **Average Variable Cost (AVC)** curve. Below minimum **AVC**, quantity supplied is zero.

## Operational Decisions and Supply - Long-Run Decision: Exit/Entry
*   **Condition:** A firm should exit the market permanently if the total revenue from producing is less than its total costs. In the long run, all costs are variable (no fixed costs).
*   **Rule:** Exit if **Total Revenue < Total Cost (TR < TC)** or, equivalently, if **Price < Average Total Cost (P < ATC)**.
*   **Entry Rule:** A firm should enter if **Price > Average Total Cost (P > ATC)**.
*   **Long-Run Supply Curve:** The portion of the firm's **Marginal Cost (MC)** curve that lies **above** its **Average Total Cost (ATC)** curve.

## Operational Decisions and Supply - Key Insights
*   The decision rules differ because fixed costs are unavoidable in the short run but can be eliminated in the long run by exiting.
*   A firm might operate at a loss in the short run (**P** < **ATC**) as long as it covers its variable costs (**P** > **AVC**), minimizing its losses compared to shutting down and still paying fixed costs.

# Long-Run Equilibrium in Perfect Competition
## Long-Run Equilibrium in Perfect Competition - Definition
*   A market state where firms have no incentive to enter or exit the industry, and economic profits are zero.

## Long-Run Equilibrium in Perfect Competition - Key Insights
*   If existing firms earn positive economic profits (**P** > **ATC**), new firms are incentivized to enter, increasing market supply, and driving down the price.
*   If existing firms incur losses (**P** < **ATC**), some firms will exit, decreasing market supply, and driving up the price.
*   This process continues until **economic profits are driven to zero**.
*   Zero economic profit occurs when **Price = Average Total Cost (P = ATC)**.
*   Since firms maximize profit where **P = MC**, the long-run equilibrium requires **P = MC** and **P = ATC**. This condition is only met at the **minimum point of the Average Total Cost curve**.
*   In long-run equilibrium, firms operate at their **efficient scale** (minimum **ATC**). The market price equals this minimum **ATC**.

## Long-Run Equilibrium in Perfect Competition - Formula
> Long-Run Equilibrium Condition: **P** = Minimum **ATC**

# Conclusion

The behavior of firms is fundamentally driven by the pursuit of maximum economic profit. This requires careful consideration of both revenues, determined largely by market structure (like perfect competition where **P**=**MR**), and costs, which stem from the production process (often exhibiting diminishing marginal returns) and include both explicit and implicit components. Firms optimize output where **MR**=**MC** and make crucial short-run (shutdown based on **P** vs. **AVC**) and long-run (exit based on **P** vs. **ATC**) operational decisions, ultimately leading perfectly competitive markets towards a long-run equilibrium where firms earn zero economic profit and operate at their efficient scale (**P**=min **ATC**).
    `
   
  },
  '4-1': {
    title: 'Understanding Monopoly and Market Power',
    content: `
# Core Concepts

*   **Market Structure:** Monopoly represents a market structure with a single seller controlling the entire output of a unique product with no close substitutes.
*   **Market Power:** Unlike firms in perfect competition, a monopolist is a price maker, facing the downward-sloping market demand curve.
*   **Profit Maximization:** Monopolists maximize profit by producing the quantity where Marginal Revenue (**MR**) equals Marginal Cost (**MC**), provided the price covers average variable costs (and total profits are non-negative).
*   **Welfare Implications:** Monopolies typically result in higher prices, lower quantities, and a deadweight loss compared to perfectly competitive markets, indicating allocative inefficiency.
*   **Price Discrimination:** Monopolists may increase profits by charging different prices to different consumer groups for the same product, based on varying willingness to pay.

# Key Terms

*   **Monopoly:** A market structure characterized by a single seller of a product with no close substitutes.
*   **Patent:** Government-granted exclusive right to produce and sell an invention for a specific period.
*   **Copyright:** Government-granted exclusive right to produce and sell creative works (e.g., software, books).
*   **Natural Monopoly:** A situation where a single firm can supply the entire market at a lower average total cost than two or more firms, typically due to high fixed costs and low marginal costs.
*   **Marginal Revenue (MR):** The change in total revenue resulting from selling one additional unit of output. For a monopolist facing a downward-sloping demand curve, **MR** is less than price.
*   **Marginal Cost (MC):** The change in total cost resulting from producing one additional unit of output.
*   **Deadweight Loss (DWL):** The reduction in total surplus (consumer surplus + producer surplus) that results from a market distortion, such as monopoly pricing, where output is below the socially efficient level.
*   **Price Discrimination:** The practice of selling the same good at different prices to different buyers.
*   **Arbitrage:** The practice of buying a good in one market at a low price and reselling it in another market at a higher price. This can undermine price discrimination.

# Causes of Monopolies
## Causes of Monopolies - Definition
Factors that prevent competing firms from entering a market, allowing a single firm to dominate.

## Causes of Monopolies - Key Insights
*   **Government Regulation:** Patents and copyrights legally restrict competition. Governments may also grant exclusive rights for national interest or public service (e.g., defense, utilities).
*   **Control of Scarce Resources:** Exclusive ownership of a critical input can create a barrier to entry.
*   **Cost Structure (Natural Monopoly):** Occurs when average total costs decline continuously over the relevant range of market demand, often due to high fixed costs and low marginal costs. This makes it difficult for new, smaller firms to compete on price.

## Causes of Monopolies - Examples
*   **Patents:** Pharmaceutical drugs (e.g., Humira).
*   **Copyrights:** Software (e.g., Microsoft Windows, Wolfram Mathematica).
*   **Government-Created:** Defense sector (e.g., HAL, DRDO in India), Railways (e.g., Indian Railways).
*   **Resource Control:** De Beers Diamond Consortium (historical control over diamond mines).
*   **Natural Monopoly:** Cellular service providers, private electricity utilities.

## Causes of Monopolies - Formula
*   For Natural Monopoly: Average Total Cost (**ATC**) = Total Cost (**TC**) / Quantity (**Q**). **ATC** decreases as **Q** increases.

# Monopolist's Pricing and Output Decision
## Monopolist's Pricing and Output Decision - Definition
The process by which a monopolist determines the quantity to produce and the price to charge to maximize profit.

## Monopolist's Pricing and Output Decision - Key Insights
*   The monopolist faces the market demand curve directly. To sell more, it must lower the price.
*   Profit maximization occurs where Marginal Revenue (**MR**) equals Marginal Cost (**MC**).
*   The price is determined by the demand curve at the profit-maximizing quantity (**Q**M).
*   An essential check: Profit must be non-negative at the **MR**=**MC** quantity; otherwise, the firm should shut down (produce **Q**=0).

## Monopolist's Pricing and Output Decision - Comparisons
*   **Monopolist:** Price maker, faces downward-sloping demand, **P** > **MR**.
*   **Perfectly Competitive Firm:** Price taker, faces horizontal demand, **P** = **MR**.

## Monopolist's Pricing and Output Decision - Formula
> **Profit (π):** π = Total Revenue (**TR**) - Total Cost (**TC**)

> **Total Revenue (TR):** **TR** = Price (**P**) × Quantity (**Q**)

> **Marginal Revenue (for linear inverse demand P = A - BQ):** **MR** = A - 2B**Q**

> **Profit Maximization Rule:** Find **Q** where **MR** = **MC**, then find **P** from the demand curve at **Q**. Ensure π ≥ 0.

## Monopolist's Pricing and Output Decision - Examples
*   **Pill Example:** Using tabular analysis with **P** = 11 - **Q**, max profit of 14 crore rupees at **Q**=4 crore pills, **P**=7 rupees.
*   **SpaceX Example (P=8-Q, TC=3+2Q):**
    *   Quadratic Profit: π = (8-**Q**)**Q** - (3+2**Q**). Max profit at **Q**=3.
    *   Marginal Principle: **MR** = 8-2**Q**, **MC** = 2. Set **MR**=**MC** → 8-2**Q**=2 → **Q**=3. Price **P** = 8-3 = 5. Profit = (5*3) - (3 + 2*3) = 15 - 9 = 6 million USD (positive, so produce **Q**=3).
    *   Shutdown Case (**P**=8-**Q**, **TC**=10+2**Q**): **MR**=**MC** → **Q**=3, **P**=5. Profit = (5*3) - (10 + 2*3) = 15 - 16 = -1 million USD (negative, so produce **Q**=0).

# Social Cost of Monopoly
## Social Cost of Monopoly - Definition
The loss of economic efficiency and welfare that arises from a monopoly's pricing and output decisions compared to a perfectly competitive market.

## Social Cost of Monopoly - Key Insights
*   Monopolies restrict output (**Q**M < **Q***) and charge higher prices (**P**M > **P***) compared to perfect competition.
*   This leads to a reduction in consumer surplus, part of which is transferred to the monopolist as producer surplus (profit), and part of which becomes **deadweight loss**.
*   **Deadweight loss** represents the value of transactions that do not occur because the monopoly price exceeds marginal cost, but is below some consumers' willingness to pay.
*   Reduced competitive pressure may also lead to less innovation over time.

## Social Cost of Monopoly - Comparisons
*   **Perfect Competition:** **P*** = **MC**, Quantity = **Q***, Allocatively efficient, Maximizes total surplus.
*   **Monopoly:** **P**M > **MC**, Quantity = **Q**M < **Q***, Allocatively inefficient, Creates **Deadweight Loss (DWL)**.

## Social Cost of Monopoly - Formula
*   **Deadweight Loss (DWL):** The area of the triangle formed between the demand curve, the marginal cost curve, the monopoly quantity (**Q**M), and the competitive quantity (**Q***).
> Area ≈ 0.5 × (**P**M - **MC** at **Q**M) × (**Q*** - **Q**M)

## Social Cost of Monopoly - Examples
*   **SpaceX Example (P=8-Q, TC=3+2Q):**
    *   Competitive Outcome: **P***=**MC**=2, **Q***=6 (from 8-**Q**=2).
    *   Monopoly Outcome: **P**M=5, **Q**M=3.
    *   **DWL** = 0.5 × (**P**M - **P***) × (**Q*** - **Q**M) = 0.5 × (5 - 2) × (6 - 3) = 0.5 × 3 × 3 = 4.5 million USD.

# Price Discrimination
## Price Discrimination - Definition
The practice by a seller of charging different prices to different consumers for the identical product or service, where the price differences are not based on cost differences.

## Price Discrimination - Key Insights
*   Allows monopolists to capture more consumer surplus and increase profits beyond what is possible with a single uniform price.
*   Requires the firm to:
    1.  Have market power.
    2.  Be able to identify and segment customers based on willingness to pay.
    3.  Prevent or limit arbitrage (resale).
*   Firms may use marketing, social norms, or product differentiation (including "damaged goods") to prevent arbitrage.

## Price Discrimination - Examples
*   Different prices for foreigners vs. citizens at Indian monuments.
*   First-time buyer discounts (cars).
*   Tiered software pricing (firm size).
*   Quantity discounts, block tariffs (utilities), two-part tariffs (amusement parks).
*   "Pink tax" (gender-based pricing).
*   IBM Laser Printer E ("damaged good").

## Price Discrimination - Comparisons
*   **Uniform Pricing:** Single price (**P**M) for all units sold. Profit = (**P**M - **ATC**) × **Q**M.
*   **Price Discrimination:** Multiple prices. Can lead to higher total profit by charging higher prices to high-valuation customers and lower prices to low-valuation customers who would not buy at **P**M.

## Price Discrimination - Examples
**MyArt Software (MC=$20):**
   *   Professionals (value $700), Amateurs (value $220). Assume 50 Professionals and 100 Amateurs based on context.
   *   Uniform **P**=$700: Sell 50 (Pro only). 
   *   Profit = 50 * ($700 - $20) = $34,000.
   *   Uniform **P**=$220: Sell 50 (Pro) + 100 (Amateur) = 150.   
   *   This yields lower profit ($30,000).
   *   Price Discrimination (P_pro=$700, P_am=$220): Sell 50 Pro, 100 Amateur. Total Profit = [Profit from Pros] + [Profit from Amateurs]. Total profit is $54,000. 
# Conclusion

Monopolies arise from barriers to entry like government regulations, resource control, or cost advantages inherent in natural monopolies. As the sole seller, a monopolist faces the market demand curve and maximizes profit by setting output where marginal revenue equals marginal cost, resulting in a price higher than marginal cost. This strategy leads to lower output and a deadweight loss compared to perfect competition, representing a social cost. Monopolists may further enhance profits through price discrimination if they can segment customers and prevent resale.

    `
   
  }
};

// Function to get a specific note by module and lesson ID
export function getNote(moduleId: number, lessonId: number) {
  const key = `${moduleId}-${lessonId}`;
  return principlesOfMicroeconomicsNotes[key as keyof typeof principlesOfMicroeconomicsNotes];
}